### ISSUE TITLE
Build instructions & path variables "Prelude not found"

### ISSUE THREAD

**Issue by cheery** [edwinb/Idris2-boot#100]
After running `make install` on Ubuntu 18 LTS, I got:

    Idris2$ ./idris2
    Uncaught error: (implicit):1:1--1:1:Prelude not found

Things seem to start working when I add the following to `.bashrc`:

    export IDRIS2_PATH="$HOME/.idris2/idris2-0.0/network:$HOME/.idris2/idris2-0.0/prelude:$HOME/.idris2/idris2-0.0/base"
    export IDRIS2_DATA="$HOME/.idris2/idris2-0.0/support"

I'd also like to know what to do in order to get idris-mode/idris-vim to work with Idris2. If it works straight out of box, tell that too.

**Comment by edwinb** [comment]
Oops, I updated the location of package paths to include the version number, but I missed an important bit and didn't notice because I had stale libraries in the old place.

**Comment by edwinb** [comment]
On the idris-vim thing, there is no support for vim at the moment. It will come. Probably the best way would be to implement the IDE protocol in vim, rather than the hack we currently use, but in the short term I'll probably just implement the hacky way.

**Comment by cheery** [comment]
@edwinb I started adding support for Idris2 into idris-vim. Though the way previous protocol is working confuses me a bit. What's the thing with load-file? How does that work actually and what did you change in its workings?

https://github.com/idris-hackers/idris-vim/issues/92
https://github.com/cheery/idris-vim
