### ISSUE TITLE
Infix operators on records

### ISSUE THREAD

**Issue by marcosh** [edwinb/Idris2-boot#103]
# Steps to Reproduce

consider the following snippet of code

```
infixr 9 +++

record Adder where
  constructor MkAdder
  (+++) : Type -> Type -> Type
```

# Expected Behavior

in Idris 1 this compiles correctly

# Observed Behavior

In Idris 2 this produces a parse error as 

```
Parse error: Expected end of input (next tokens: [symbol (, symbol +++, symbol ), symbol :, Type, symbol ->, Type, symbol ->, Type, end of input])
```

**Comment by edwinb** [comment]
I've just changed the parser to allow any name in a record field. I probably just didn't think of this as a possibility.

**Comment by marcosh** [comment]
thanks for the quick fix!
