### ISSUE TITLE
Let bindings are not substituted in types

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#107]
Might be related to #87 .

# Steps to Reproduce
Create the file `Foo.idr`:
```
g : Nat -> Type
g Z = Nat
g _ = String

h : g Z -> g Z -> Nat
h = let u = g Z in
    \ i : u => \ j: g Z => 0
```
The point is to get the type-checker to check that `u` and `g Z` unify after we bind `g Z` to `u`.

# Expected Behavior
```
$ idris2 --check Foo.idr 
1/1: Building Foo (Foo.idr)
```
This works fine with Idris 1.

# Observed Behavior
```
$ idris2 --check Foo.idr 
1/1: Building Foo (Foo.idr)
Foo.idr:7:5--8:1:While processing right hand side of Main.h at Foo.idr:6:1--8:1:
When unifying u and Nat
Mismatch between:
	u
and
	Nat
```

**Comment by edwinb** [comment]
Yes, that's right, and it is a change from Idris 1. There's all sorts of complications with `let` having reduction behaviour, especially when trying to propagate them through `case` and `with`. So for consistency, `let x = t in e` is equivalent to `(\x => e) t`.

You can write a local definition if you want this behaviour, however. Something like:

    let u : ?
        u = g Z in

then you should get the reduction behaviour you want. See also #67

**Comment by ohad** [comment]
Thanks Edwin. Changing to `let u : ...` gives the expected behaviour. 

But something isn't quite right with the annotated version (or I misunderstand how it works). 
Changing `Foo.idr` to:
```
g : Nat -> Type
g Z = Nat
g _ = String

h : g Z -> g Z -> Nat
h = let u : Type
        u = g Z in
    let v : u 
        v = Z in
    \ i : u => \ j: g Z => 0
```
I get:
```
$ idris2 -c Foo.idr 
1/1: Building Foo (Foo.idr)
Foo.idr:9:13--9:15:While processing right hand side of Main.h at Foo.idr:6:1--11:1:
While processing right hand side of 1109:v at Foo.idr:9:9--9:15:
When unifying Nat and u
Mismatch between:
	Nat
and
	u
```

**Comment by edwinb** [comment]
Hmm, it's probably treating `u` as an implicitly bound name. Might have to rethink the rules here a bit.
