### ISSUE TITLE
Couldn't parse declaration

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#111]
The file `issues/Foo/Foo.idr`:
```
module issues.Foo.Foo
```
type checks fine:
```
nicola@lt561:~/gitlab/botta/Idris2Libs$ idris2 issues/Foo/Foo.idr
Welcome to Idris 2 version 0.0. Enjoy yourself!
issues.Foo.Foo>
```
However, the file `issues/Double/Foo.idr`:
```
module issues.Double.Foo
```
fails to type check with
```
nicola@lt561:~/gitlab/botta/Idris2Libs$ idris2 issues/Double/Foo.idr
issues/Double/Foo.idr:1:14--1:14:Parse error: Couldn't parse declaration (next tokens: [symbol ., Double, symbol ., identifier Foo, end of input])
Welcome to Idris 2 version 0.0. Enjoy yourself!
Main>
```
Am I missing something obvious here? Thanks, Nicola

**Comment by clayrat** [comment]
I suspect this is due to `Double` being a keyword, as defined in https://github.com/edwinb/Idris2/blob/master/src/Parser/Lexer.idr#L104

**Comment by nicolabotta** [comment]
@clayrat: that sounds very plausible but  it wasn't the case in Idris 1 and it is not clear to me why it should be the case in Idris 2. The error message is also not very illuminating ...

**Comment by edwinb** [comment]
I don't think they need to be keywords. I'm changing it so that the primitives are reserved names instead, meaning that you can use them in namespaces, but not as the names of identifiers.
