### ISSUE TITLE
Name leak in definition-level type ascribed let-binding

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#115]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce
Type-check the following file:
```
x : let a : Nat
        a = 1
  in Nat
x = a


y : let a : Nat
        a = 1
    in Nat    
y = let a : Nat
        a = 1
    in 1
```
# Expected Behavior
`x` should not type-check, with error:
```
Undefined name a
```
and `y` should type-check.

But if `y` doesn't type-check, with error `a is already defined`, then `x` should type-check.

# Observed Behavior
Neither definition type-checks:
```
Foo.idr:4:5--7:1:While processing right hand side of Main.x at Foo.idr:4:1--7:1:
Undefined name a
Foo.idr:11:9--12:9:While processing right hand side of Main.y at Foo.idr:11:1--14:1:
1109:a is already defined
```

**Comment by edwinb** [comment]
Nested names like this are decorated with the parent name, and it only knows about nested scopes. I suspect it's picking the same name for both `a` in `y`, decorating `a` with `y` in both cases, because I didn't think of this possibility.

This might be a good one for anyone interested in digging through the code (I don't have much time for hacking at the moment). It all happens in `TTImp.Elab.Local`.

**Comment by ohad** [comment]
Thanks, I'll give it a go then.

**Comment by ohad** [comment]
What is the intended behaviour?

From your answer it seems like both `x` and `y` type-check correctly and in `y`, the term-level `a` shadows the type-level `a`?

I'd have expected the type and the term to have separate scopes, so `x` doesn't type-check while `y` does.

**Comment by ohad** [comment]
Ah, ok, I get it. I think.

**Comment by ohad** [comment]
OK, pull request #121 fixes it, hopefully in the intended way and without introducing new bugs

```
$ cat Foo1.idr 
x : let a : Nat
        a = 1
    in Nat
x = a
$ idris2 -c Foo1.idr 
1/1: Building Foo1 (Foo1.idr)
Foo1.idr:4:5--6:1:While processing right hand side of Main.x at Foo1.idr:4:1--6:1:
Undefined name a
$ cat Foo2.idr 
y : let a : Nat
        a = 1
    in Nat    
y = let a : Nat
        a = 1
    in 1
$ idris2 -c Foo2.idr 
1/1: Building Foo2 (Foo2.idr)
$
```

**Comment by edwinb** [comment]
Yes, that;'s what I think the behaviour should be. Thanks!
