### ISSUE TITLE
Holes in uncreachable cases

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#126]
Probably related to #108 

# Steps to Reproduce
Load `Foo.idr`:
```
f : Bool -> Nat
f True = 0
f True = ?help
f False = 1
```
into the REPL:
```
$ idris2 Foo.idr 
Welcome to Idris 2 version 0.0.0.  Enjoy yourself!
Main> :t help
```

# Expected Behavior
```
Main> :t help
-------------------------------------
help : Nat
```

# Observed Behavior
```
Main> :t help
(interactive):1:4--1:8:Undefined name help
```

If we remove the first line in `Foo.idr` so that the clause with the hole is reachable, we do get the expected behaviour:
```
$ cat Foo.idr 
f : Bool -> Nat
f True = ?help
f False = 1
$ idris2 Foo.idr 
1/1: Building Foo (Foo.idr)
Welcome to Idris 2 version 0.0.0.  Enjoy yourself!
Main> :t help
-------------------------------------
help : Nat
```

**Comment by edwinb** [comment]
Hmm, that's surprising. They are elaborated after all! I wonder if something about fixing up the holes in the linearity checking phase breaks it due to the hole being normalised away.
