### ISSUE TITLE
The function type constructor is unreferencable.

### ISSUE THREAD

**Issue by VladimirMarko** [edwinb/Idris2-boot#128]
# Steps to Reproduce
Just type `:t (->)`.

Also, try to type-check this code adapted from Haskell's `Control.Category`:
```
interface Category (cat : Type -> Type -> Type) where
  id : cat a a
  compose : cat a b -> cat b c -> cat a c

Category (->) where
  id = \x => x
  compose f g = \x => g (f x)
```

# Expected Behavior
```
Main> :t (->)
-> : Type -> Type -> Type
```
Also, the adapted code type-checks.

# Observed Behavior

## Idris2 version 0.0.0:
```
Main> :t (->)
Parse error: Unrecognised command (next tokens: [identifier t, symbol (, symbol ->, symbol ), end of input])
```
```
Category.idr:7:1--7:1:Parse error: Couldn't parse declaration (next tokens: [identifier Category, symbol (, symbol ->, symbol ), where, identifier id, symbol =, symbol \, identifier x, symbol =>])
```
## Idris version 1.3.2:
```
Idris> :t (->)
(input):1:7:
  |
1 | :t (->)
  |       ^
-> is not a valid operator
```
```
Type checking ./Category.idr
Category.idr:7:14:
   |
12 | Category (->) where
   |              ^
-> is not a valid operator
```

**Comment by clayrat** [comment]
This is a tricky one because `->` generally means "dependent function", so this behaviour is probably expected. It might be useful to have some heuristic to restrict it to a non-dependent version in some cases though.

**Comment by VladimirMarko** [comment]
So the actual type of the function type constructor is actually
`->> : (a : Type) -> (a -> Type) -> Type`,
where writing `a -> b` is merely syntactic syntactic sugar for `a ->> (\_ => b)`?

**EDIT:**
OK, so this appears to be the case.
So just like I can box a normal function with:
```
data IndFun : Type -> Type -> Type where
  MkIndFun : (a -> b) -> IndFun a b

boxedIndId : IndFun a a
boxedIndId = MkIndFun (\x => x)
```
I can also box a dependent function with:
```
data DepFun : (a : Type) -> (dependency : (a -> Type)) -> Type where
  MkDepFun : ((x : a) -> dependency x) -> DepFun a dependency

boxedDepId : DepFun a (\_ => a)
boxedDepId = MkDepFun (\x => x)       
```
Neat.

**EDIT 2:**
However, `\x => x` is not actually a dependent function. If I had one, say:
```
funFun : (n: Nat) -> Vect n Nat
funFun n = funFun' n n where
  funFun' : (n : Nat) -> Nat -> Vect n Nat
  funFun' Z _ = Nil
  funFun' (S k) n = n :: funFun' k n
```
How would I then get the `dependency` function?
That is, how do I box `funFun`?
```
boxedFunFun : DepFun Nat (?extractDependency funFun)
boxedFunFun = MkDepFun funFun 
```
Is there a built-in function for `?extractDependency`?
I would not know how to search for it. Something like `:search ((x : a) -> dependency x) -> a -> Type` does predictably not work.
Normally, one would use destructuring in this kind of scenario, but it's not available here.

**Comment by edwinb** [comment]
Unlike Haskell, `(->)` is a binder, not a constructor, so being able to reference it makes no more sense than being able to reference lambda or let. This should probably be in the FAQ.

(It is briefly mentioned here: https://github.com/idris-lang/Idris-dev/wiki/Unofficial-FAQ#why-cant-i-treat---as-a-function)
