### ISSUE TITLE
Nesting a namespace in a parameter block gives incorrect results

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#132]
This is also buggy in Idris 1, but in a different way

# Steps to Reproduce
```
$ cat Foo.idr
parameters (n:Nat)
  public export
  namespace X
    foo : Bool
    foo = True

  U : Bool
  U = foo
$ idris2 Foo.idr
```
# Expected Behavior
```
1/1: Building Foo (Foo.idr)
Main> U 0
True
```
# Observed Behavior
```
1/1: Building Foo (Foo.idr)
Foo.idr:4:11--6:3:While processing right hand side of Main.X.foo at Foo.idr:4:5--6:3:
When unifying Bool and Nat -> Bool
Mismatch between:
	Bool
and
	Nat -> Bool
```
What _does_ type-check, is the follows:
```
$ cat Foo.idr
parameters (n:Nat)
  namespace X
    public export   
    foo : Bool
    foo n = True

  U : Bool
  U = foo 1
$ idris2 Foo.idr
1/1: Building Foo (Foo.idr)
Main> U 0
True
```
so the nesting half-works, adding the extra parameter to the type, but not the declaration.

If we try to compile this file in Idris 1, we get:
```
Type checking ./Foo.idr
Foo.idr:7:7-9:
  |
7 |   U = foo
  |       ~~~
When checking right hand side of Main.U with expected type
        Bool

Too many arguments for Main.X.foo
```
which I guess happens because the nested definition doesn't add the extra parameters?

**Comment by edwinb** [comment]
When it processes a parameters block, it looks inside for the names which need expanding. And apparently I forgot to get it to look inside namespaces...

By the way, I'd expect your first example to fail because `foo` isn't exported from the namespace, although that's not the issue here.

**Comment by ohad** [comment]
Yes, I saw that, but simply adding the following to `TTImp.TTImp.defName` doesn't fix it:
```
defName (INamespace _ _ _ nns) = concatMap defName nns
```
(I may have got the number of arguments to INamespace wrong here, I'm typing from memory.)

At some point I thought it's because the code that elaborates the types of declarations uses `SubRefl` and so abstracts over everything in the set of nested declarations, instead of the opposite, but changing it to `EmptyRefl` (appropriately defined) also didn't fix it.

**Comment by edwinb** [comment]
I think it's because in `processParams` it also assumes that the names in the block will be in the current namespace, which is not true in this case:

     defNames <- traverse inCurrentNS (definedInBlock ds)

There's probably a better way to handle this. I was trying to reuse the existing machinery for `where`/`let` as far as possible.

Perhaps `definedInBlock` could do the job of calculating the fully qualified names instead.

**Comment by ohad** [comment]
OK, I'll see if I can do something about it. Thanks!
