### ISSUE TITLE
Nesting a record in a parameter block gives incorrect results

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#138]
Probably another variant of #132 

# Steps to Reproduce
`Foo.idr`:
```
import Data.Vect

parameters (n : Nat)
  record Foo where
    constructor Bar
    Gnat : Vect n Nat

foo : Foo 1
foo = Bar [0] 
```
```
$ idris2 -c Foo.idr
```
# Expected Behavior
```
1/1: Building Foo (Foo.idr)
```
# Observed Behavior
```

1/1: Building Foo (Foo.idr)
Foo.idr:4:3--8:1:While processing constructor Main.Foo.Bar at Foo.idr:4:3--8:1:
When unifying Nat -> Type and Type
Mismatch between:
	Nat -> Type
and
	Type
Foo.idr:9:7--11:1:While processing right hand side of Main.Foo.foo at Foo.idr:9:1--11:1:
Undefined name Bar
```

Also broken in Idris1:
```
- + Errors (1)
 `-- Foo.idr line 8 col 4:
     When checking type of Main.foo:
     Too many arguments for Main.Foo
```

**Comment by edwinb** [comment]
I've pushed a fix for this, but also note that since `Bar` is part of the parameters block, it takes an additional argument `n`. It could be implicit too, but I think it's better for consistency that all names have the parameter argument added explicitly.

(edit: typo)

**Comment by ohad** [comment]
Agreed! Thanks!
Is there a way to parametrise over implicit parameters?
