### ISSUE TITLE
Build fails with "no such variable clockTime"

### ISSUE THREAD

**Issue by drone29a** [edwinb/Idris2-boot#14]
Full error is below. I searched for a definition of `clockTime` but didn't find anything. I'm building by running `make idris2` in a freshly-cloned repo.

```
Type checking ./Core/Context.idr
./Core/Context.idr:1815:7-1830:20:
     |
1815 |     = do opts <- getSession
     |       ~~~~~~~~~~~~~~~~~~~~~ ...
When checking right hand side of logTime with expected type
        Core a

When checking an application of function Core.Core.coreLift:
        No such variable clockTime

make: *** [idris2] Error 1
```

**Comment by edwinb** [comment]
Hi - see issue #2. You need the latest Idris master, as documented at the start of INSTALL.md

**Comment by drone29a** [comment]
Ah, I had only checked open issues. Sorry about that. Thanks for the quick reply.
