### ISSUE TITLE
Network.Socket functions not marked as exported

### ISSUE THREAD

**Issue by sysvinit** [edwinb/Idris2-boot#152]
The functions in the `network` package which are exposed through the `Network.Socket` module are not marked as exported. This means that they cannot be accessed by applications importing that module, which makes the library unusable.

This looks like it's the result of a copy/paste error from the Idris 1 networking code in `contrib` -- the Idris 1 networking library in `contrib` uses an `%access export` directive, which isn't supported under Idris 2, and this evidently hasn't been replaced by visibility annotations on each of the definitions in the Idris 2 library.

**Comment by abailly** [comment]
I realised that when I tried to use the network lib on my own project...
