### ISSUE TITLE
Type Indices not used in computing missing cases

### ISSUE THREAD

**Issue by JoeyEremondi** [edwinb/Idris2-boot#157]
I'm assuming this is a "just not implemented yet" issue, but I thought I should document it for posterity. 

Right now, it looks like the totality checker just makes sure all combinations of constructors are covered, but doesn't check indices, so it reports impossible cases as missing.

# Steps to Reproduce

```
module NNat
--    
data NNat = NZ | NS NNat
--
zsym : (x : NNat) -> x = NZ -> NZ = x
zsym NZ Refl = Refl
```

# Expected Behavior
The REPL shoudl report `zsym` as total

# Observed Behavior
```
NNat> :missing zsym
NNat.zsym:
zsym (NS _) _
NNat> :total zsym
NNat.zsym is not covering all cases
```

**Comment by edwinb** [comment]
Idris 1 behaves the same way - if you try the case it suggests, it will type check, even though the second argument is an empty type.

It will accept that a case is impossible if an argument has an index which conflicts will an index in the same position in all the constructors (e.g. `Fin Z`, where `Z` conflicts will all the constructors of `Fin`).
It's not clever enough to spot cases like this one (deciding whether a type is empty is undecidable after all).

That said, there is still an issue here, which is that adding the case

    zsym (NS _) Refl impossible

is not enough to convince it it's total. I will fix this.

**Comment by edwinb** [comment]
The coverage checker now looks at impossible clauses to build the case tree. My error above is now fixed, so I'll close this as expected behaviour.
