### ISSUE TITLE
Incorrect treatment of variable-length top-level pattern matches

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#168]
# Steps to Reproduce
```
$ cat Foo.idr 
T : Nat -> Type
T Z = Bool -> Nat
T (S n) = Nat -> T n

X : (n : Nat) -> T n
X Z         k     = ?hole0
--X (S (S n)) k1 k2 = ?hole2
X (S n)     k     = ?hole1


$ idris2 --no-banner Foo.idr
Main> 
```
# Expected Behavior
Either:
```
Main> :t hole0
 1 k : Bool
-------------------------------------
hole0 : Nat
Main> :t hole1
   n : Nat
 1 k : Nat
-------------------------------------
hole1 : T n
```
or some kind of error about the wrong number of arguments (see more below).

# Observed Behavior
```

Main> :t hole0
 1 k : Bool
-------------------------------------
hole0 : Bool -> Nat
Main> :t hole1
   n : Nat
 1 k : Nat
-------------------------------------
hole1 : Nat -> T n
```

This isn't some glitch with how holes are printed, were we to stick a `Nat` in the first case, we'll get an error.

The rationale for expecting Idris to report an error about the wrong number of arguments is that were we to uncomment the line `X (S (S n)) k1 k2 = ?hole2`, we'll get the error:
```
Foo.idr:6:1--7:1:Patterns for Main.X have differing numbers of arguments
```
so we might not expect to be able to uncurry arguments that are a result of type-level computation. 
Ideally, I'd prefer to have such differing number of arguments, and so allow the first example to type-check, though I appreciate it might not be easy to implement with the current type-checker design.

**Comment by edwinb** [comment]
I've encountered this one too a few times and just worked around it. It's irritating though, I'll look into it next!
