### ISSUE TITLE
weird error when trying to build

### ISSUE THREAD

**Issue by shmish111** [edwinb/Idris2-boot#17]
When I `make` I get
```
Type checking ./Core/Core.idr
./Core/Core.idr:402:12:
    |
402 |   traverse : (a -> Core b) -> Binder a -> Core (Binder b)
    |            ^
When checking type of traverse:
Can't disambiguate name: Language.Reflection.Binder, Core.TT.Binder

make: *** [idris2] Error 1
```
This is strange because I can't see `Language.Reflection.Binder` anywhere in the Idris2 code base, why does it think `Core.idr` is importing it somehow?

**Comment by shmish111** [comment]
I'm closing because I managed to build using the `master` branch of Idris 1 however I don't understand the error message, seems strange.

**Comment by stepcut** [comment]
I got this same error when trying to build Idris2 using idris 1.3.2 from hackage.

**Comment by shmish111** [comment]
I just managed to build idris2 on OSX using the idris 1 from `cabal update && cabal install idris`

**Comment by stepcut** [comment]
For some reason I get this error if Idris 1.3.2 is built via `nix` but not if I install Idris 1.3.2 via `cabal-install`. The `nix` packaging for `idris` is fairly involved and does special things so you can select what packages are available in the environment. That extends to the built-in libraries including base/prelude.

So, I have a work around, but it still remains mysterious how this error crops up in some situations but not others.

**Comment by shmish111** [comment]
I didn't manage to install 1.3.2 on OSX via nix, it is broken (and marked as broken), what OS are you on?

**Comment by stepcut** [comment]
I am on OS X. I am using an old snapshot of nixpkgs that only has idris 1.3.1, so I just checked out the source code and added an override,

```
idris = super.haskell.lib.dontCheck (haskell-self.callCabal2nix "idris" ./pkgs/Idris-dev {});
```

If you are serious about digging into this bug I can put together a `.nix` file that duplicates the issue.

**Comment by shmish111** [comment]
I don't really have time at the moment TBH but it would be better to fix on nixpkgs `master` anyway.

**Comment by ghost** [comment]
I can build idris2 via nix, but I get this error when I try building idris2 from a nix-shell using `nix-shell --pure '<nixpkgs>' -A idris2`. I'm using the nixos-unstable channel and following overlay
```
self: super: {
  idris2 = super.stdenv.mkDerivation rec {
    name = "idris2";
    version = "0.1.0";
    src = fetchGit {
      url = "https://github.com/edwinb/Idris2.git";
      # rev = "0cbc3b839688ca2de83b6103a637ce4519dc4ea5";
      rev = "59503712f39422d9cea52f051aa2eb8c01281eca";
    };

    buildInputs = [ self.gmp self.clang_10 self.chez (with self.idrisPackages; with-packages [ base contrib ])];

    patchPhase = ''
        patchShebangs ./tests/ideMode/ideMode002/gen_expected.sh
    '';

    buildPhase = ''
        make idris2 libs OPT="-O2"
    '';
    installPhase = ''make install OPT="-O2" PREFIX="$out"'';
  };
}
```

I've build idris via
```
haskellPackages = unstable.haskell.packages.ghc883.override {
      overrides = hsSelf: hsSuper: rec {
        idris = hsSelf.callCabal2nixWithOptions "idris" (fetchGit {
            url = "https://github.com/idris-lang/Idris-dev.git";
            rev = "ecb49fa1b78847ec00fc13bd915e55b6acc2d0e5";
        }) "--no-check" {};
      };
    };
```

in my ~/.config/nixpkgs/config.nix

**Comment by ghost** [comment]
It gets even weirder. I've build the git version of idris now with cabal, and now Idris2 typechecks, but only on console. The emacs mode using the same idris binary, complains 
```
`-- ./Core/Core.idr line 454 col 11:
     When checking type of traverse:
     Can't disambiguate name: Language.Reflection.Binder, Core.TT.Binder
```

**Comment by evertedsphere** [comment]
I have this same issue trying to compile Idris 2 (current master) from source using Idris 1 (current master) compiled from source. I had to disable tests when building Idris 1 (I too am on NixOS) because the version of Idris 1 in nixpkgs (on the `nixos-unstable` branch) is broken because of the problem with the current Hackage version (1.3.2) not compiling with Cabal 3.0 due to the hooks in the Setup.hs.
