### ISSUE TITLE
Very High RAM usage when building idris2.

### ISSUE THREAD

**Issue by soverysour** [edwinb/Idris2-boot#170]
Hi, this issue is about very high memory usage while compiling Idris2.

I haven't seen an issue like this anywhere in this repository, so this is why I'm creating this one.

Basically, I've set up idris (1.3.2) on path and tried to compile idris2 - all the modules were `Type checked` (that's what I could tell from the logs), and afterwards (this is still in the `idris --build idris2.ipkg` step in the `idris2` rule in the `Makefile`) one CPU core would spike to 100% (the other cores didn't seem to do anything) and memory usage would keep going up - it used up to 6 GBs before I stopped it.

I'm on Ubuntu 19.04.

My questions are: is this a known behaviour? Can I limit that step so as to have it behave reasonably and still build the project properly?

**Comment by ziman** [comment]
AFAIK, this sudden blowup is caused by the C compilation step after the code is generated. On my machine, the Idris stage gradually fills about 4G of RAM and then the C stage quickly takes another 4G of RAM. I usually just enable swap for this because not all this memory is used at the same time.

**Comment by soverysour** [comment]
I added some more swap and ran through the above - installation successful.

Thanks for your help!

**Comment by nickdrozd** [comment]
I am seeing the same problem, but my laptop is puny and there is no more memory to allocate. Maybe reopen this issue? It seems like something that shouldn't happen.

**Comment by melted** [comment]
The problem is with the Idris codegen rather than Idris 2, so the issue doesn't belong here either way.
