### ISSUE TITLE
Allowed to pattern match on erased arguments in type constructor

### ISSUE THREAD

**Issue by christian-public** [edwinb/Idris2-boot#178]
The pull request #176 by @ohad tempted me to experiment with putting multiplicity on the arguments of a type constructor (See example below). I then noticed that I am allowed to pattern match on erased arguments in a type constructor. Is that meant to be allowed?

# Steps to Reproduce

Create a file named `ErasedArg.idr` with the following content:

```idris
data MyMaybe : (0 x : Type) -> Type where
  MyNothing : MyMaybe a
  MyJust : a -> MyMaybe a

nameOf : Type -> String
nameOf (MyMaybe Bool) = "MyMaybe Bool"
nameOf _ = "Unknown"

main : IO ()
main = do
  putStrLn (nameOf (MyMaybe Bool))
  putStrLn (nameOf (MyMaybe Int)) -- Also matches `MyMaybe Bool` because the argument to `MyMaybe` is erased at run-time.
  putStrLn (nameOf Int)
```

Run the example using: `idris2 --exec main ErasedArg.idr`

Example was tested on the latest commit (bf5b229).

# Expected Behavior

I would expect the compiler to complain that I am trying to pattern match on an erased argument, giving an error similar to:
```
ErasedArg.idr:5:1--6:1:Attempt to match on erased argument Bool in Main.nameOf
```

# Observed Behavior

Program outputs:
```
MyMaybe Bool
MyMaybe Bool
Unknown
```

**Comment by edwinb** [comment]
The strange thing here is that it's actually treating the `Bool` as a variable. If you add another case (say for `MyMaybe Int`) then it complains as it should. I think there's a check missing in the case tree compiler.

**Comment by christian-public** [comment]
Thanks! That is interesting. I don't think I am able to fix this issue in the compiler (I am not familiar with how case trees work).

**Comment by edwinb** [comment]
The real fix is to check erased arguments properly, rather than the hacky way it works at the minute. It is, er, quite a large patch, as you'll see shortly!

**Comment by christian-public** [comment]
Thanks, this is great. It works perfectly! :-)

**Comment by edwinb** [comment]
Perhaps unsurprisingly, it showed up a couple of things that probably shouldn't have worked. I've been wanting to come up with a better approach to this for a while, so thanks for the prod!
