### ISSUE TITLE
Failure to infer an implicit argument

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#184]
# Steps to Reproduce
```
import Data.Vect

Signature : Type
Signature = (n : Nat ** Vect n Nat)


op : (sig : Signature) -> Type
op sig = (arity : Nat ** Elem arity (snd sig))

arity : {sig : Signature} -> op sig -> Nat
arity f = DPair.fst f


Monoid_Sig : Signature
Monoid_Sig = (_ ** 
             [0
             ,2
             ])

Times_Op : op Monoid_Sig
Times_Op = (_ ** There Here)

Two : Nat
Two = arity Times_Op
```

# Expected Behavior
```
$ idris2 Foo.idr
1/1: Building Foo (Foo.idr)
Foo> 
```
# Observed Behavior
$ idris2 Foo.idr
1/1: Building Foo (Foo.idr)
Foo.idr:24:13--26:1:While processing right hand side of Main.Two at Foo.idr:24:1--26:1:
  Can't solve constraint between:
  S (S Z)
  and
  fst ?sig
```

This type-checks fine in Idris1. I think it should type-check in Idris2, as the type-checker should be able to unify the `Monoid_Sig` in the type of `Times_Op` with the implicit parameter.
Am I missing something?

**Comment by edwinb** [comment]
There isn't enough information for it, given `op sig`, to infer `sig` here, since `op` is a function, and it only uses `snd sig` in any case. So I think this is correct behaviour, and Idris 1 is wrong (Idris 1 guesses too much during unification, which has been the cause of lots of problems...).
