### ISSUE TITLE
Silently allowing undefined names inside function applications in data/interface decls

### ISSUE THREAD

**Issue by mrkgnao** [edwinb/Idris2-boot#190]
I couldn't think of a less convoluted example, sorry.

# Steps to Reproduce

```idris
module BindingTestCase

data Foo : (Bool -> Type) -> Bool -> Type where
  MkFoo : {cond : Bool -> Type} -> {bool : Bool} 
      -> cond bool -> Foo cond bool

ite : Bool -> Type
ite = \y => if y then Bool else Int

data Bar : Type where
  MkBar : Foo (\y => if y then Bool else Int) True -> Bar

-- Undefined name z, fails in repl or with idris2 --check

-- data Qux : Type where
--   MkQux : Foo (\y => if z then Bool else Int) True -> Qux

-- Works in both the repl and idris2 --check
data Baz : Type where
  MkBaz : Foo (\y => ite z) True -> Baz
  --                    ^^^

main : IO ()
main = print "!"
```

# Expected Behavior
Compile failure with `Undefined name z`.

# Observed Behavior
```
❯ idris2 --check BindingTestCase.idr
1/1: Building BindingTestCase (BindingTestCase.idr)
```

**Comment by edwinb** [comment]
It doesn’t implicitly bind names in case bocks (which is what if statements elaborate via) but otherwise it’s implicitly binding the z. It’s not clear that the rules as they stand are the right rules, but it is behaving as I expect.

I will think about what the implicit binding rules should be for if...

**Comment by edwinb** [comment]
I've thought about this a bit, and I think the behaviour you're seeing is consistent with the rules: any variable beginning with a lower case letter in an argument position will be implicitly bound. It doesn't look under `case` or `if` for such names, and it's probably best that it doesn't.
