### ISSUE TITLE
Error building Idris2: No such variable clockTime

### ISSUE THREAD

**Issue by logicchains** [edwinb/Idris2-boot#2]
I checked out this repo (commit 38443e23a31497321a87544e4e5969b58307620b), ran `make idris2`, and got the following error. I'm using Version 1.3.1 of Idris1 to build. 
(Note that I'm not very familiar with Idris so it's possible I'm doing something horribly wrong). 
```
Type checking ./Core/Context.idr
./Core/Context.idr:1790:7-1805:20:
     |
1790 |     = do opts <- getSession
     |       ~~~~~~~~~~~~~~~~~~~~~ ...
When checking right hand side of logTime with expected type
        Core a

When checking an application of function Core.Core.coreLift:
        No such variable clockTime

make: *** [Makefile:10: idris2] Error 1
```
When I grep the repo for `clockTime` I see no other references outside of that file.

**Comment by ska80** [comment]
Hello Jonathan,

You need Idris 1 from ‘master'.

**Comment by edwinb** [comment]
Yes, that's right, `clockTime` is in master but not Idris 1.3.1. I can't easily do a release of 1.3.2 at the moment (see the list) but I'll do it as soon as I can.
