### ISSUE TITLE
can't make latest version 

### ISSUE THREAD

**Issue by vfrinken** [edwinb/Idris2-boot#214]
On MacOS 10.14.6 (Mojave)

The `sed` command on line 56 in the Makefile fails with 
`sed -i '1 s|^.*$|char* idris2_prefix = "/Users/<my username>/.idris2";|' dist/idris2.c`

if I comment that line out (because it doesn't change anything in the dist/idris2.c file as far as I can tell), it gives me

```
$ make
Using Idris 1 version: 1.3.2
Building Idris 2 version: 0.0.0-edc3e2a4c
idris --build idris2.ipkg
Entering directory `./src'
Leaving directory `./src'
make -C dist
make -C rts
make[2]: Nothing to be done for `build'.
clang   idris2.c -o idris2 -I rts -L rts -lidris_rts -lpthread -lgmp -lm
idris2.c:241878:22: warning: 'tmpnam' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
    RVAL = MKSTR(vm, tmpnam(GETPTR(LOC(1))));
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:186:1: note: 'tmpnam' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:180:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((deprecated(_msg)))
                                                      ^
1 warning generated.
make -C libs/prelude IDRIS2=../../idris2
../../idris2 --build prelude.ipkg
1/3: Building Builtin (Builtin.idr)
2/3: Building PrimIO (PrimIO.idr)
3/3: Building Prelude (Prelude.idr)
make[1]: *** [all] Illegal instruction: 4
make: *** [prelude] Error 2
```

**Comment by ska80** [comment]
I found the place where Idris 2 crashes on exit:

https://github.com/edwinb/Idris2/blob/edc3e2a4cdfe12a3baa426bb4e91324cceed6315/dist/rts/idris_rts.c#L139

Commenting this line lets Idris 2 exit without crashing.

Here is a more detailed error message in LLDB:

```
$ lldb ./idris2 
(lldb) target create "./idris2"
Current executable set to './idris2' (x86_64).
(lldb) run
Process 34616 launched: '/Users/kamil/.local/idris/dist/idris2' (x86_64)
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.0.0-edc3e2a4c
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/                                           

Welcome to Idris 2.  Enjoy yourself!
Main> :exit
Bye for now!
Process 34616 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00007fff6e55948e libsystem_platform.dylib`_os_unfair_lock_corruption_abort + 23
libsystem_platform.dylib`_os_unfair_lock_corruption_abort:
->  0x7fff6e55948e <+23>: ud2    

libsystem_platform.dylib`_os_once_gate_recursive_abort:
    0x7fff6e559490 <+0>:  movl   %edi, %eax
    0x7fff6e559492 <+2>:  leaq   0x932(%rip), %rcx         ; "BUG IN CLIENT OF LIBPLATFORM: Trying to recursively lock an os_once_t"
    0x7fff6e559499 <+9>:  movq   %rcx, 0x29c285e8(%rip)    ; gCRAnnotations + 8
Target 0: (idris2) stopped.
(lldb) 
```

**Comment by edwinb** [comment]
Hmm, I'll try this on my Mac shortly and see if I can reproduce it... The `sed` line is only really needed if you're installing directly from C, to make sure the prefix is right, so safe to comment out if building from Idris. Possibly I need to check the `-D` flags for the `rts` build.

This is all to make distribution easier, to make it installable on machines without Idris 1. There are probably bits of the `rts` code that need tweaking.

**Comment by edwinb** [comment]
One thing that might cause this is that it turns out the flags are inconsistent for building `idris2.c` and building the library support. I've just pushed a thing that might fix that part of the problem (I can't test it on Mac just yet though).

It would be useful to see the error that `sed` gives - perhaps I'm doing something linux specific by accident.

**Comment by ska80** [comment]
> It would be useful to see the error that `sed` gives - perhaps I'm doing something linux specific by accident.

I have sent a small pull request #215 to fix the error that`sed` gives.  It is the difference in the options handling between bsd and gnu versions that causes the error.

**Comment by edwinb** [comment]
Have the recent patches fixed this one? I'd guess they should have but I'll leave it open until @vfrinken confirms.

**Comment by vfrinken** [comment]
Yes, I can confirm, it works

**Comment by edwinb** [comment]
Excellent, thanks, I'll close now.
