### ISSUE TITLE
Record constructors should not be elaborated in 1st pass of mutual blocks

### ISSUE THREAD

**Issue by ziman** [edwinb/Idris2-boot#217]
# Steps to Reproduce

```idris
mutual
  record A where
    b : B
  record B where
    a : A
```

# Expected Behavior

The program typechecks.

# Observed Behavior

```
mut.idr:3:9--5:3:While processing constructor Main.A.A at mut.idr:2:3--5:3:
Undefined name B
```
If I define `A` using `data` instead of `record`, it typechecks fine.

I suspect that constructors of records are elaborated in the first pass of `mutual` blocks, while they should be elaborated in the second pass.

**Comment by ziman** [comment]
Of course it's more complicated:
```idris
  -- Get the declaration to process on each pass of a mutual block
  -- Essentially: types on the first pass
  --    i.e. type constructors of data declarations
  --         function types
  --         interfaces (in full, since it includes function types)
  --         records (in full, similarly)
  --         implementation headers (i.e. note their existence, but not the bodies)
  -- Everything else on the second pass
  getDecl : Pass -> PDecl -> Maybe PDecl
```

Types of projections can probably be processed in the first pass but their bodies, as well as the type of the constructor, should be deferred to the second pass.

**Comment by edwinb** [comment]
I suppose it'll need something a bit like data declarations, where there's a specific constructor for forward declarations of data.

**Comment by edwinb** [comment]
I just changed it to do the same as Idris 1. Probably it should do the projection types, but it's unnecessarily fiddly for now.

Also, as I've probably said in various places before, I am inclined to remove `mutual` blocks soonish, because they're not really mutual, it's just sugar for forward declarations, and that could lead to confusion.
