### ISSUE TITLE
Add a way of running tests individually

### ISSUE THREAD

**Issue by ysangkok** [edwinb/Idris2-boot#23]
Many tests are failing when I "make test", so I want to run a single test and manually compare its result with contents of the `expected` file. So I try this:

```
~/Desktop/Idris2-master/tests/idris2/basic011 $ sh ./run ../../../idris2
(implicit):1:1--1:1:Prelude not found
(implicit):1:1--1:1:Prelude not found
(implicit):1:1--1:1:Prelude not found
```

So I must be doing something wrong? Is this the correct way to try to run an individual test? Would be nice if there was some documentation for this.

**Comment by edwinb** [comment]
That is how I'd do it, yes. It'd be useful if the test runner had some way of running a subset of tests (say, even just by name matching).

Documentation for lots of things would be nice, but somebody has to write it first! I've written a bit for various aspects of the system, and others have helped with commenting etc, but I can't anticipate everything people might want to do at this stage.

**Comment by kevinboulain** [comment]
By chance, were you using `make -j`?

I think there is a small ordering problem with the makefile which may be why you are seeing tests failures as I also am when I pull and ask for a parallel build:
```
idris2/interactive010: success
idris2/interactive011: success
Type checking ./Core/TTC.idr
idris2/interactive012: success
idris2/interface001: success
idris2/interface002: FAILURE
```
Looks like it's compiling Idris and running the tests at the same time.

**Comment by ysangkok** [comment]
Yeah, I think I may have used `-j`. But I'd consider that a separate issue, this one is about documentation. I think I can send a PR for this within the next few days.
