### ISSUE TITLE
libc bindings in std?

### ISSUE THREAD

**Issue by hirrolot** [edwinb/Idris2-boot#232]
How about adding libc bindings to the standard library of Idris in a separate module so people could reuse them? Or I'd better make a separate library for this stuff?

I could work on this in my free time.

**Comment by edwinb** [comment]
I don't really know what you mean by libc bindings. There's a lot of them, and it's likely that a lot of what libc does is provided in a different way by the Idris libraries. If you do want to add more, though, we'd certainly welcome contributions (best to add to `contrib` first, or to a new package if you think there's a better way of organising it).

**Comment by hirrolot** [comment]
Ok, thx. I mean functions from the C standard library, such as `wcstombs`, `memcpy`, `memmove`, etc.

**Comment by edwinb** [comment]
These don't really make sense in Idris, being about low level representations of data, memory management, etc. They might make sense in some more specialised library for low level programming, but not really in the standard library. So I'd suggest working on this sort of thing in a separate library, then we'll see how it goes.
