### ISSUE TITLE
AnyPtr can prove Void

### ISSUE THREAD

**Issue by neriglissar** [edwinb/Idris2-boot#240]
Hi, the following example produces an invalid proof of Void by nesting data structures three times and the use of AnyPtr. The example is as minimal as I could get it. Curiously, even changing AnyPtr to another datatype breaks the example. 
```idris
data SimpleData = PtrAndSize AnyPtr Int

record Complicated where
  constructor MkComplicated 
  simple : SimpleData 

record MoreComplicated where
    constructor MkMoreComplicated
    something : Complicated

record EvenMoreComplicated where
    constructor MkEvenMoreComplicated
    somethingEven : MoreComplicated 

data TooComplicatedToBeTrue : (something : EvenMoreComplicated) -> Type where
    SomethingVeryComplicatedIs :
        TooComplicatedToBeTrue
            (MkEvenMoreComplicated (MkMoreComplicated (MkComplicated (PtrAndSize addr len))))

showing  :  (something : EvenMoreComplicated) -> (TooComplicatedToBeTrue something) -> Void
showing _ SomethingVeryComplicatedIs impossible
```

# Steps to Reproduce
See [this file](https://github.com/neriglissar/too-complicated/blob/master/TooComplicatedToBeTrue.idr)

# Expected Behavior
We should expect the REPL to say

`showing _ SomethingVeryComplicatedIs impossible is not a valid impossible case`

# Observed Behavior

Idris2 loads the file without objections.

**Comment by edwinb** [comment]
This is because I still haven't got around to doing external data types correctly. It thinks AnyPtr is an empty type, even though it's not. Thanks for reporting - this gives me a reminder to do it properly!

**Comment by neriglissar** [comment]
> This is because I still haven't got around to doing external data types correctly. It thinks AnyPtr is an empty type, even though it's not. Thanks for reporting - this gives me a reminder to do it properly!

Ah, you're right - I'm actually wrong about the nested types - I was probably doing too many things at once. But it's good to know that we can safely work with an internal datatype in the meantime!
