### ISSUE TITLE
Irrelevant definitions are not accessible from REPL :t

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#257]
# Steps to Reproduce
```
$ cat ReplRelevance.idr 
0 foo : Nat -> Nat
foo n = 0
$ idris2 ReplRelevance.idr 
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.0.0-7c71d5dd4
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/                                           

Welcome to Idris 2.  Enjoy yourself!
Main> :t foo
Main.foo : Nat -> Nat
Main> :t foo 0
```
# Expected Behavior
```
Main> :t foo 0
0 : Nat
```

# Observed Behavior
```
Main> :t foo 0
(interactive):1:4--1:9:Main.foo is not accessible in this context
```

**Comment by edwinb** [comment]
That's because it checks them in a relevant context. You can set the evaluator to do the same as the evaluator at the type level with `:set eval tc`.

Perhaps we should also have a command that sets the multiplicity of the REPL. My feeling is that the current default is the right one, though.

**Comment by ohad** [comment]
Ah, I didn't know we can do that. I guess it would be documented once we implement `:help set` to take arguments.
