### ISSUE TITLE
Conditional compilation

### ISSUE THREAD

**Issue by hirrolot** [edwinb/Idris2-boot#262]
Is there a way to achieve conditional compilation in Idris2? More precisely, I need to somehow let a user specify one of three options: `A`, `B`, or `C`, and, based on the choice, export different functions from my library.

**Comment by timmyjose** [comment]
@Hirrolot I think you might have better luck asking over on reddit.com/r/idris. The community there is pretty helpful and reasonably active!

**Comment by hirrolot** [comment]
Ok, thx )
