### ISSUE TITLE
Can't build Idris2 on Mac OS X

### ISSUE THREAD

**Issue by symbiont-arnaud-bailly** [edwinb/Idris2-boot#3]
I am trying to build Idris2 on Mac OS X. I have previously installed ChezSchem, building with `./configure --threads && make && make install`:

```
$ scheme
Chez Scheme Version 9.5.2
Copyright 1984-2019 Cisco Systems, Inc.

>
```

when I run `make` into a freshly checked out directory, I got the following errors in tests:

```
Found Chez Scheme at /usr/local/bin/scheme
Exception: variable make-thread-parameter is not bound
chez/chez001: FAILURE
Exception: variable make-thread-parameter is not bound
chez/chez002: FAILURE
Exception: variable make-thread-parameter is not bound
chez/chez003: FAILURE
Exception: variable make-thread-parameter is not bound
chez/chez004: FAILURE
Exception: variable make-thread-parameter is not bound
chez/chez005: FAILURE
Exception: variable make-thread-parameter is not bound
chez/chez006: FAILURE
Exception: variable make-thread-parameter is not bound
chez/chez007: FAILURE
119/126 tests successful
make[1]: *** [test] Error 1
make: *** [test] Error 2
```

**Comment by edwinb** [comment]
I'm not an expert on Chez Scheme, but does this mean that your build doesn't have threading support? How did you install it?

**Comment by sonfangos** [comment]
Arnaud, I copied-and-pasted your own command above when I installed Chez Scheme on macOS 10.14.5 from ChezScheme-9.5.2.tar.gz last night, and I had no problems going on to install Idris 2. FTR, here are my more-or-less accurate/complete dear-diary installation notes:

> Installed Idris 2 by doing all the following:
> 
> Install ChezScheme-9.5.2 via tarball with the command:
> ./configure --threads && make && make install
> 
> cabal install highlight-versions
> 
> export PATH=$PATH:.cabal-sandbox/bin
> 
> Make dir 'Idris-Master' in home dir for Idris master.
> 
> in home/Idris-Master dir run:
> git clone git://github.com/idris-lang/Idris-dev dev
> 
> cd dev
> 
> cabal sandbox init
> 
> cabal update
> 
> cabal install --only-dependencies
> 
> make
> 
> Add following to .bash_profile:
> export PATH="$HOME/Idris-Master/dev/.cabal-sandbox/bin:$PATH"
> 
> Add following to .bashrc:
> alias idris='$HOME/Idris-Master/dev/.cabal-sandbox/bin/idris'
> 
> . ~/.bash_profile
> 
> . ~/.bashrc
> 
> In home dir run:
> git clone https://github.com/edwinb/Idris2.git
> 
> cd Idris2
> 
> make idris2
> 
> make install
> 
> make test
> 
> Add following to .bash_profile:
> export PATH="$HOME/.idris2/bin:$PATH"
> 
> . ~/.bash_profile
> 
... or something like that.

**Comment by abailly** [comment]
@sonfangos @edwinb I have provided a tiny PR to add a note to not forget to install Chez Scheme with `--threads` configuration file. Might or might not be adequate but my issue was that I installed first _without_ the flag and did not _uninstall_ so the binaries were not replaced.
