### ISSUE TITLE
Chez: Exception: variable make-thread-parameter is not bound

### ISSUE THREAD

**Issue by ysangkok** [edwinb/Idris2-boot#32]
# Steps to Reproduce
1. `make install`

# Expected Behavior
All tests pass.

# Observed Behavior
Chez tests return "Exception: variable make-thread-parameter is not bound".

Chez version: 9.5.3 (master from July 16th)

**Comment by clayrat** [comment]
Seems like a duplicate of https://github.com/edwinb/Idris2/issues/3

**Comment by ysangkok** [comment]
Ah, sorry.
