### ISSUE TITLE
find-ipkg doesn't load the ipkg dependencies

### ISSUE THREAD

**Issue by berewt** [edwinb/Idris2-boot#349]
Dependencies are ignored when you use `--find-ipkg`.

# Steps to Reproduce

`test.ipkg`:

```
package test

depends = contrib
modules = Foo
```

`Foo.idr`:
```
module Foo

import Data.List.TailRec
```

```
$ idris2 --find-ipkg --check Foo.idr
```

# Expected Behavior

It typechecks.

# Observed Behavior

```
   idris2 --find-ipkg --check Foo.idr
(toplevel):1:1--1:1:Data.List.TailRec not found
```

# Comments

it may be enough to load the package in the `findIpkg` method of `Package.idr`. I've tried it locally and it works. I'm going to PR the change.

**Comment by edwinb** [comment]
Closing since @berewt's recent PR fixes this.
