### ISSUE TITLE
Auto-search is slow when restricting a heterogenous list to a predicate type

### ISSUE THREAD

**Issue by christian-public** [edwinb/Idris2-boot#36]
(I initially wrote this as a comment on a closed issue, but I think it makes more sense to add a new issue. Sorry about that.)

It unfortunately seems like the patch for #25 reduces the performance of some uses of auto-search.

After updating my Erlang codegen-branch to include all changes from Idris 2's master branch, I noticed that the [`Erlang` module](https://github.com/chrrasmussen/Idris2/blob/erlang-codegen/libs/base/Erlang.idr) would not finish type-checking. I found that the change in performance happened specifically in the commit https://github.com/edwinb/Idris2/commit/677ddea9c5fcc17dc124a017fc09640b0744f452 ("Only check determining arguments at the top level").

The `Erlang` module include functions (e.g. `erlCall`) that require a proof that its arguments only consist of types that have a mapping to Erlang. These types are specified in a predicate type called [`ErlType a`](https://github.com/chrrasmussen/Idris2/blob/erlang-codegen/libs/base/Erlang.idr#L127-L170).

# Steps to Reproduce

I have reduced the `Erlang` module to the following code, that still exhibit the problem:

```
data ErlList : List Type -> Type where
  Nil : ErlList []
  (::) : x -> ErlList xs -> ErlList (x :: xs)

data ErlType : Type -> Type where
  ETInteger : ErlType Integer
  ETString : ErlType String

data ErlTypes : List Type -> Type where
  ETErlTypesNil : ErlTypes []
  ETErlTypesCons : (ErlType x, ErlTypes xs) => ErlTypes (x :: xs)

erlCall : ErlList xs -> {auto prf : ErlTypes xs} -> ()
erlCall args = ()

foo : ()
foo = erlCall [1, 2, 3]
```

(I kept the original names of the types/functions to make it easier to cross-reference the code in the `Erlang` module.)

# Expected Behavior

Timings when type-checking this sample program with different amount of arguments to `erlCall`:

| Args to `erlCall` | Before patch |
|-------------------|--------------|
| []                | 0.08s        |
| [1]               | 0.09s        |
| [1, 2]            | 0.09s        |
| [1, 2, 3]         | 0.09s        |
| [1, 2, 3, 4]      | 0.10s        |

# Observed Behavior

Timings when type-checking this sample program with different amount of arguments to `erlCall`:

| Args to `erlCall` | After patch |
|-------------------|-------------|
| []                |      0.08s  |
| [1]               |      2.17s  |
| [1, 2]            |      5.16s  |
| [1, 2, 3]         |      7.98s  |
| [1, 2, 3, 4]      |      10.50s |

**Comment by edwinb** [comment]
Oops, it looks like I missed the case for data constructors in the determining argument check, so it's running the search before it's ready and keeps hitting a hole (because I removed the non-top-level check) and branching a lot... sorry about that!

The fix for this is easy enough. Checking that nothing is else broken as a result, perhaps less so...

**Comment by edwinb** [comment]
Let me know if this fixes the overall problem - I'll reopen if not.

**Comment by christian-public** [comment]
Thanks, the fix works perfectly!

Idris 2 is amazing. Thank you, Edwin :)
