### ISSUE TITLE
SegmentFault on String

### ISSUE THREAD

**Issue by andylokandy** [edwinb/Idris2-boot#379]
# Steps to Reproduce

```idris
module Main

import Data.String.Extra

thisGoesWrong : String
thisGoesWrong = (join "a" []) ++ ""

main : IO ()
main = putStrLn $ thisGoesWrong
```

# Expected Behavior

Output `""`

# Observed Behavior

If I eval `thisGoesWrong` in repl, the compiler will throw `segment fault`; if I execute `main`, the compiler throws `Exception in substring: 1 and 0 are not valid start/end indices for ""`.

Both `(join "a" [])` and `"" ++ ""` are fine, but it breaks when they come together.

**Comment by edwinb** [comment]
It looks like the substring primitive doesn't check bounds properly, resulting in a dodgy string. Chez throws an exception in this case, and C crashes. The primitive should probably return an empty string in these cases rather than crash.
