### ISSUE TITLE
Can't build on Windows using Idris 1.3.2

### ISSUE THREAD

**Issue by zenntenn** [edwinb/Idris2-boot#41]
I just updated to Idris 1.3.2 using the Windows binary.  I don't think this is related to the Chez Scheme problem, because it didn't get anywhere close to running tests.  

Here is what's in the command line, running on Windows 10, on a system where I have successfully built smaller Idris 1 projects:

Microsoft Windows [Version 10.0.18362.239]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\zente\Documents\Idris\Idris2>make idris2
idris --build idris2.ipkg
Entering directory `.\src'
Type checking .\Core\Context.idr
.\Core\Context.idr:26:13-35:15:
   |
26 |     PMDef : (alwaysReduce : Bool) -> -- always reduce, even when quoting etc
   |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ...
When checking type of Core.Context.PMDef:
No such variable CaseTree

.\Core\Context.idr:60:1-8:
   |
60 | Show Def where
   | ~~~~~~~~
When checking type of Core.Context.Def implementation of Prelude.Show.Show:
When checking argument ty to type constructor Prelude.Show.Show:
        No such variable Def

.\Core\Context.idr:155:1-175:26:
    |
155 | public export
    | ~~~~~~~~~~~~~ ...
When checking type of Core.Context.MkGlobalDef:
No such variable Def

make: *** [Makefile:12: idris2] Error 1

C:\Users\zente\Documents\Idris\Idris2>idris --version
1.3.2

C:\Users\zente\Documents\Idris\Idris2>

**Comment by melted** [comment]
Hi!

I fixed up basic Windows support, but I haven't yet made it user-friendly. To make it work correctly you need to have a custom.mk that sets IDRIS2_PATH and IDRIS2_DATA.

Mine looks like
```
PREFIX ?= ./.idris2
CDIR=$(shell cygpath -w `pwd`)
export IDRIS2_PATH = ${CDIR}/libs/prelude/build;${CDIR}/libs/base/build
export IDRIS2_DATA = ${CDIR}/support
```

Then you need to ensure that those environment variables exist and pointing at the right dirs when you run the exe.

You also need to have the environment variable CHEZ set to where your scheme is. It tries to autodetect it in various unixy places otherwise.

This should be improved. There should be a check for windows in the make file. We should put the lib stuff somewhere in AppData if not overridden and it should at least look in the PATH for chez scheme. I'll get to it sooner or later put feel free to send Edwin a PR before then.

**Comment by zenntenn** [comment]
Can I just double checking that it's specifically chez that's needed and
not one of the other two, even though the installation instructions say any
of the three are fine?

**Comment by melted** [comment]
I only changed the Chez backend: https://github.com/edwinb/Idris2/pull/4/files

I guess you could put in analogous change in another backend. But really, it should have a PATH search mechanism for all of them.

**Comment by melted** [comment]
And, yeah, there's a line in the ipkg file that needs to be uncommented (and the other opts commented out). Because there's no mechanism to send options to only one platform. That can only be fixed in the Idris 1 implementation.

**Comment by zenntenn** [comment]
OK, so I created the same custom.mk, confirmed that it is being used (because if I put in any errors in it I get the errors when doing make idris2), added the location of a cygpath to my PATH, confirmed that is there, added a CHEZ enviornment variable pointing at where I installed CHEZ, commented the opts and uncommented the windows settings for opts in the .ipkg file, and now I'm getting the exact same errors as in my bug report.

C:\Users\zente\Documents\Idris\Idris2>make idris2
idris --build idris2.ipkg
Entering directory `.\src'
Type checking .\Core\Context.idr
.\Core\Context.idr:26:13-35:15:
   |
26 |     PMDef : (alwaysReduce : Bool) -> -- always reduce, even when quoting etc
   |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ...
When checking type of Core.Context.PMDef:
No such variable CaseTree

.\Core\Context.idr:60:1-8:
   |
60 | Show Def where
   | ~~~~~~~~
When checking type of Core.Context.Def implementation of Prelude.Show.Show:
When checking argument ty to type constructor Prelude.Show.Show:
        No such variable Def

.\Core\Context.idr:155:1-175:26:
    |
155 | public export
    | ~~~~~~~~~~~~~ ...
When checking type of Core.Context.MkGlobalDef:
No such variable Def

make: *** [Makefile:12: idris2] Error 1

C:\Users\zente\Documents\Idris\Idris2>

**Comment by zenntenn** [comment]
By the way, I think the issue is before any of these things would apply.  If I just try to build the .ipkg I get the same error:

C:\Users\zente\Documents\Idris\Idris2>idris --build idris2.ipkg
Entering directory `.\src'
Type checking .\Core\Context.idr
.\Core\Context.idr:26:13-35:15:
   |
26 |     PMDef : (alwaysReduce : Bool) -> -- always reduce, even when quoting etc
   |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ...
When checking type of Core.Context.PMDef:
No such variable CaseTree

.\Core\Context.idr:60:1-8:
   |
60 | Show Def where
   | ~~~~~~~~
When checking type of Core.Context.Def implementation of Prelude.Show.Show:
When checking argument ty to type constructor Prelude.Show.Show:
        No such variable Def

.\Core\Context.idr:155:1-175:26:
    |
155 | public export
    | ~~~~~~~~~~~~~ ...
When checking type of Core.Context.MkGlobalDef:
No such variable Def

**Comment by zenntenn** [comment]
I also get the same error when I try to load src\Core\Context.idr in the repl, and also when I try to typecheck in both VS Code and Atom.

**Comment by zenntenn** [comment]
Cleaning out all the .ibc files fixed the issue.  Really not sure why make clean didn't remove them, at least not the ones in the ./src subdirectories.
