### ISSUE TITLE
Mismatch: expected behaviour?

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#44]
The program
```
module issues.Mismatch

interface Monad m => FooBar m where

  Foo : {A : Type} -> A -> m A -> Type

  Bar : {A : Type} -> m A -> Type

  foo : {A : Type} -> (a : A) -> (ma : m A) -> Foo a ma -> Bar ma
```
fails to type check with
```
issues.Mismatch> :r
1/1: Building issues.Mismatch (issues/Mismatch.idr)
issues/Mismatch.idr:9:3--12:1:While processing right hand side of issues.Mismatch.foo at issues/Mismatch.idr:9:3--12:1:
When unifying __bind_Bar arg and Bar ma
Mismatch between:
	A
and
	{A:222}
issues.Mismatch>
```
The issue can be solved by replacing
```  
  foo : {A : Type} -> (a : A) -> (ma : m A) -> Foo a ma -> Bar ma
```  
with
```
  foo : {A : Type} -> (a : A) -> (ma : m A) -> Foo a ma -> Bar {A} ma
```
I am not sure whether this is an Idris2 bug or the expected behaviour, it seems to me that the type checker should be able to deduce the value of the implicit argument of `Bar` in this case.

**Comment by edwinb** [comment]
What if `Bar` is implemented by a function `const Int`? Then it's not necessarily true to deduce that the implicit is `A`.

I can't remember if I've implemented this yet, but you can express the constraint that `Bar` is implemented by a data type by writing:

    data Bar : {A : Type} -> m A -> Type

On the other hand, given that `Bar` is universally quantified at this stage, the constraint has to be true for all possible `Bar`s so perhaps it's okay. I will think further.

I think Idris 1 allows this, but only because of an incorrect hack in unification.

**Comment by edwinb** [comment]
As an aside, this error message really needs improving - in situations where unification fails because it can't infer an implicit argument, it could probably spot that that's what the issue is and report which implicit is the problem, although I can't immediately think how to achieve that

**Comment by edwinb** [comment]
So thinking about this a bit, I think the fact that the record representing the interface type checks means that there should be enough information to build an appropriate top level type for foo and not rely on unification filling bits in which it might not be able to.

The error message should still be better, but that's a separate thing really.

**Comment by edwinb** [comment]
Turns out it was a lot less complicated than that. It was a bit of the unfiication algorithm I'd implemented in Blodwen but hadn't yet in Idris2... we're up to date there now (apart from a really fancy thing that I'm not sure I'm going to do, but that's another matter).

**Comment by nicolabotta** [comment]
Great, thanks Edwin! Best, Nicola
