### ISSUE TITLE
Implicit record fields

### ISSUE THREAD

**Issue by clayrat** [edwinb/Idris2-boot#46]
# Steps to Reproduce
```
module Temp

import Data.Vect

record Foo where
  constructor MkFoo
  filler : Int
  {size : Nat}
  foos  : Vect size String

isEmpty : Foo -> Bool
isEmpty f = size f == 0
```

# Expected Behavior
This compiles and works as expected both with and without the `filler` field in Idris 1.3.

# Observed Behavior
Without `filler`:
```
Temp.idr:8:3--8:3:Parse error: Expected end of input (next tokens: [identifier foos, symbol :, identifier Vect, identifier size, String, identifier isEmpty, symbol :, identifier Foo, symbol ->, identifier Bool])
```

With `filler`:
```
Temp.idr:12:13--12:20:While processing right hand side of Temp.isEmpty at Temp.idr:12:1--13:1:
Undefined name size
```

**Comment by edwinb** [comment]
Hmm, this seems likely to be a problem with parsing - at least, I hope it is, rather than something deeper! I'll take a look at some point soon, but perhaps this would be a good place for someone else to get involved... (also, I'd really like a much nicer and faster parser if anyone is so inclined!)

**Comment by clayrat** [comment]
Ironically, I encountered this when trying to port https://github.com/gallais/idris-tparsec :)

**Comment by clayrat** [comment]
I haven't figured out the parsing error, but in the second case it looks like the getter for `size` actually has the name `imp_size`, this behavior is defined in https://github.com/edwinb/Idris2/blob/master/src/TTImp/ProcessRecord.idr#L77. Is there a reason it needs to be that way?

**Comment by clayrat** [comment]
Regarding the parser error, I've found out that without `filler` it parses `size` as an explicit field, and then the closing brace makes it think it's the EOF, though I'm still unsure why the implicit branch fails.

**Comment by clayrat** [comment]
Ok, the [implicit branch](https://github.com/edwinb/Idris2/blob/master/src/Idris/Parser.idr#L1124-L1129) fails because the [first branch](https://github.com/edwinb/Idris2/blob/master/src/Parser/Support.idr#L515-L519) of `blockAfter` commits after seeing `{`. Would it suffice to just swap branches in `blockAfter`?

**Comment by clayrat** [comment]
@edwinb I think the proper fix is to push the [parser for constructor](https://github.com/edwinb/Idris2/blob/master/src/Idris/Parser.idr#L1154-L1156) under `blockAfter`, since the current setup seems to allow stuff like
```
record Foo where
  constructor MkFoo 
  { 
   {size : Nat}
   foos : Vect size String 
  }
```
whereas we probably want 
```
record Foo where {
  constructor MkFoo  
   {size : Nat}
   foos : Vect size String 
  }
```
?

**Comment by edwinb** [comment]
I think the `imp_size` thing is a thing Idris 1 did for implicit record fields to avoid name clashes, so I just carried it over. I don't see a good reason why it should still be that way (or even why it might have been in the first place) especially given that records live in their own namespace.
