### ISSUE TITLE
Can't have re-exporting modules

### ISSUE THREAD

**Issue by clayrat** [edwinb/Idris2-boot#48]
# Steps to Reproduce
Foo.idr
```
module Foo

public export 
foo : Nat -> Nat 
foo = S
```
Bar.idr
```
module Bar

bar : String -> Nat
bar = length
```
Temp.idr
```
module Temp

import public Foo
import public Bar
```
temp.ipkg
```
package temp

modules = Foo
        , Bar
        , Temp
```

# Expected Behavior
Everything compiles
# Observed Behavior
```
$ idris2 --build temp.ipkg 
1/3: Building Foo (Foo.idr)
2/3: Building Bar (Bar.idr)
Temp.idr:5:1--5:1:Parse error: Couldn't parse declaration (next tokens: [end of input])
```

**Comment by edwinb** [comment]
I think for some reason the parser wants to have at least one declaration, but there's no need for that. It's probably an easy one for someone to fix and learn a small amount about the parser at the same time...
