### ISSUE TITLE
Implicits (and auto implicits) don't get passed to "with" clauses

### ISSUE THREAD

**Issue by clayrat** [edwinb/Idris2-boot#57]
# Steps to Reproduce
```
module Temp

import Data.List

safeStrHead : (s : String) -> {pr : NonEmpty (unpack s)} -> Char
safeStrHead s with (unpack s)
  safeStrHead s | [] = absurd pr
  safeStrHead s | (c::_) = c
```
# Expected Behavior

Compiles successfully.

# Observed Behavior

```
Temp.idr:7:31--8:3:While processing right hand side of Temp.with block in 1163 at Temp.idr:7:3--8:3:
Undefined name pr
```
Can be made to compile by changing to: 
```
safeStrHead : (s : String) -> {pr : NonEmpty (unpack s)} -> Char
safeStrHead {pr} s with (unpack s)
  safeStrHead {pr} s | [] = absurd pr
  safeStrHead s | (c::_) = c
```

When `pr` is made an auto implicit, both the version above and the one with `@{pr}` work (but not the initial one without manual introductions).

**Comment by edwinb** [comment]
This needs a small update to the code which matches with clauses against the parent clause. I think it's easy to fix, based on some experimenting, but I'm going to use it as an excuse to tidy up the code for `with` a bit, so it might take a few days unless I'm the right sort of bored.
