### ISSUE TITLE
Nat is not optimized correctly in all cases, leading to run-time error

### ISSUE THREAD

**Issue by christian-public** [edwinb/Idris2-boot#62]
When using `Nat`'s successor (`S`) as a function, it is not optimized correctly, leading to run-time error.

If I disable the `natHack` and `natHackTree` in `Compiler.CompileExpr` module, the example below works as expected. I can also rewrite the expression `S` to `(\n => S n)` and it will now be optimized correctly.

I first discovered this issue when using the range syntax to create a `List Nat`. It was the functions `rangeFromTo` and `rangeFrom` from the `Nat` implementation of `Range` that lead me to the problem, more specifically the expression `countFrom x S`.

I am able to reproduce this issue using both the Chez and Racket code generators (I did not try Chicken).

# Steps to Reproduce

Create a file called `Nat.idr` and execute it: `idris2 --exec main Nat.idr`
```
myS : Nat -> Nat
myS n = S n

myS_crash : Nat -> Nat
myS_crash = S

main : IO ()
main = do
  printLn (S Z)
  printLn (myS Z)
  printLn (myS_crash Z)
```

# Expected Behavior

Output:
```
1
1
1
```

# Observed Behavior

Output:
```
1
1
Exception in number->string: #(1 0) is not a number
```

**Comment by edwinb** [comment]
I'm not certain, because I've only quickly looked at the compiler code, but I think the optimisation might be working under the assumption that all constructors are saturated, but I don't see the code which does constructor saturation.
