### ISSUE TITLE
Interfaces and records: unexpected behavior

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#64]
The program
```
module issues.FiniteAsRecord

import Data.Fin
import Data.Vect

tail : {A : Type} -> {n : Nat} -> (Fin (S n) -> A) -> (Fin n -> A)
tail f = f . FS

toVect : {A : Type} -> {n : Nat} -> (Fin n -> A) -> Vect n A
toVect {n =   Z} _ = Nil
toVect {n = S m} f = (f FZ) :: (toVect (tail f))

record Iso a b where
  constructor MkIso
  to : a -> b
  from : b -> a
  toFrom : (y : b) -> to (from y) = y
  fromTo : (x : a) -> from (to x) = x

record Finite t where
  constructor MkFinite
  card : Nat
  iso  : Iso t (Fin card)  

foo : (Finite t) => Vect (card t) t
foo = toVect (from iso)
```
type checks fine in Idris 2. But
```
module issues.FiniteAsInterface

import Data.Fin
import Data.Vect

tail : {A : Type} -> {n : Nat} -> (Fin (S n) -> A) -> (Fin n -> A)
tail f = f . FS

toVect : {A : Type} -> {n : Nat} -> (Fin n -> A) -> Vect n A
toVect {n =   Z} _ = Nil
toVect {n = S m} f = (f FZ) :: (toVect (tail f))

record Iso a b where
  constructor MkIso
  to : a -> b
  from : b -> a
  toFrom : (y : b) -> to (from y) = y
  fromTo : (x : a) -> from (to x) = x

interface Finite t where
  card : Nat
  iso  : Iso t (Fin card)  

foo : (Finite t) => Vect (card t) t
foo = toVect (from iso)
```
fails to type check with
```
nicola@cirrus:~/gitlab/botta/Idris2Libs$ idris2 issues/FiniteAsInterface.idr 
1/1: Building issues.FiniteAsInterface (issues/FiniteAsInterface.idr)
issues/FiniteAsInterface.idr:24:27--24:33:While processing type of issues.FiniteAsInterface.foo at issues/FiniteAsInterface.idr:24:1--25:1:
When unifying Nat and Type -> Nat
Mismatch between:
	Nat
and
	Type -> Nat
issues/FiniteAsInterface.idr:25:1--26:1:No type declaration for issues.FiniteAsInterface.foo
Welcome to Idris 2 version 0.0. Enjoy yourself!
issues.FiniteAsInterface>
```
Is this the expected behavior? 

In absence of a mechanism for referring to the cardinality of `t` in the signature of `foo`, one is forced to implement `foo` as a default method of the `Finite` interface. This leads to "fat" interfaces which is usually considered a bad design.  Does this mean that, in order to keep interfaces "thin" we should use records instead of interfaces? What are the advantages/disadvantages of records vs. interfaces?

**Comment by edwinb** [comment]
You're giving `card` an argument, and `card` doesn't take any arguments. You're treating it as if it has type `Type -> Nat` whereas it actually has type `Nat`, which is exactly what the error message says. The location range it gives you points exactly at the `card t` in the type of `foo`.

It type checks fine as a record because record projects take an explicit argument. Probably what you want is `card {t}` but I haven't tested this.

**Comment by nicolabotta** [comment]
Right, with
```
foo : (Finite t) => Vect (card {t}) t
foo = toVect (from iso)
```
one gets
```
issues.FiniteAsInterface> :r
1/1: Building issues.FiniteAsInterface (issues/FiniteAsInterface.idr)
issues/FiniteAsInterface.idr:25:7--26:1:While processing right hand side of issues.FiniteAsInterface.foo at issues/FiniteAsInterface.idr:25:1--26:1:
Trying to use irrelevant name t in non-linear context
issues.FiniteAsInterface>
```
This comes from the definition of `foo` though. Commenting out this definition makes the program type check.

**Comment by edwinb** [comment]
That's because `toVect` claims to need the type argument, even though it really doesn't. And `t` is irrelevant. So it's trying to use the irrelevant name `t` when calling `toVect`. This is all correct behaviour so I'm going to close this.
