### ISSUE TITLE
Best way to add readline support?

### ISSUE THREAD

**Issue by donald-pinckney** [edwinb/Idris2-boot#7]
I'm interested in helping  to make the REPL better, in particular readline / history support. I'm wondering what your thoughts are about the best way to do this? I know of [baseline-idris](https://github.com/laserpants/baseline-idris) which FFI wraps readline, but if we use this, it would require installing both readline and baseline-idris as dependencies in order to build idris2. Any thoughts about other ways to do this, or should I just go ahead and use baseline-idris?

**Comment by david-christiansen** [comment]
What about implementing the REPL separately, and communicating with Idris over the IDE protocol? This would allow you to depend on anything you want, and to use the same interface to talk to Idris 1 and Idris 2.

**Comment by donald-pinckney** [comment]
That's interesting. Do you think roughly all the features / commands of the Idris 1 REPL can be implemented via the IDE protocol? (Apologies I don't know much about the IDE protocol)

**Comment by david-christiansen** [comment]
Almost all can be directly implemented, and the protocol can be extended to
support the few things not in it, like :e.

**Comment by david-christiansen** [comment]
Here's a slightly longer explanation (though still from the phone, sorry!)

The protocol is essentially a machine-readable syntax to the REPL. It has a
few places where there's more information (where the REPL emits ANSI
escapes for colors, the protocol provides metadata like documentation
overviews and type signatures that clients can use for their own coloring
or other presentation), but it's mostly a thin wrapper around the same
functions. Any missing commands can be added as wrappers with about 20
lines of Haskell in Idris 1 at least, and I suspect that it's similar in
Idris 2.

The extra info exposed in the protocol can also enable fancy features like
the Emacs mode has, such as interactive error messages and hyperlinked
documentation, but that can be a stretch goal :-)

**Comment by donald-pinckney** [comment]
Ok this sounds cool. I can probably start by poking at the Emacs or Atom mode source to see how to start connecting to Idris and interacting with the IDE mode. I can probably start hacking around on it this weekend.

**Comment by david-christiansen** [comment]
This document may also be useful:
http://docs.idris-lang.org/en/latest/reference/ide-protocol.html

**Comment by david-christiansen** [comment]
Also, if the protocol needs to be updated to support this use case, then it
should be updated. Please don't see it as something completely set in stone
- backwards compatibility is great, and should be preserved as much as
possible, but I don't think it should get in the way of being useful.

I wrote much of the Emacs mode, feel free to email me or ask here if you
have questions about its implementation.

**Comment by edwinb** [comment]
Implementing it as a separate executable is definitely the right way to go, I think. It will need more support in the IDE protocol but I expect you could add what you need as you go.

**Comment by edwinb** [comment]
Closing since it's more a question than an issue, and there hasn't been discussion for a few days...

**Comment by donald-pinckney** [comment]
Sorry I've been a bit busy lately, but I have a prototype which I've been meaning to push up to a repo soon.

**Comment by edwinb** [comment]
It's mostly that I'm trying to keep things under control for myself by keeping the issue tracker to actual issues with an objectively definable resolution for the moment. Questions are fine, but probably still better to ask on the mailing list.

Actually I'd quite like a way to separate reporing of bugs, which really need to be dealt with, from proposals and questions, for which it would be nice to have open ended discussion without having to go through and manually tag things. Anyone have any ideas?

**Comment by david-christiansen** [comment]
Some projects have seperate repositories for discussions and proposals.
This has a few nice features:
1. Version control of proposal documents
2. Discussions are separated from bug-tracking
3. Proposal documents don't clutter up the main repository and its history
4. People who are averse to mailing lists can be directed to a forum that
they'll actually use, so there may be a bigger chance of keeping non-bugs
out of the bug tracker

Den ons. 17. jul. 2019 kl. 11.03 skrev Edwin Brady <notifications@github.com

**Comment by edwinb** [comment]
@david-christiansen I think I might do something like that, with a pointer in an issue template or something like that. I don't want to stop people asking questions or proposing things (quite the opposite in fact) but I would like a clear separation. Experience from Idris 1 suggests I might get more fixed that way. We'll see...

**Comment by donald-pinckney** [comment]
Here is the repository in which I am currently working on the REPL: [https://github.com/donald-pinckney/IdrisRepl](https://github.com/donald-pinckney/IdrisRepl).

Currently I have implemented the `:l <filename>` command, and it seems to work fine with both Idris and Idris 2 via IDE protocol. Most of the other commands should be pretty fast now...

When some other place is setup for discussions / proposals, etc., I can move this to there.

**Comment by david-christiansen** [comment]
I look forward to checking it out!

If you have questions about the highlighting, I'd be happy to set up a
quick video call with you to explain it. That might be fastest.

Den ons. 17. jul. 2019 kl. 13.15 skrev Donald Pinckney <
notifications@github.com>:

**Comment by donald-pinckney** [comment]
I’ll have to set this aside for a few days, but I would be happy to talk early next week.
