### ISSUE TITLE
Interpreter does not clean opened files when loading/reloading files

### ISSUE THREAD

**Issue by abailly** [edwinb/Idris2-boot#74]
The interpreter blows up very quickly when one loads a file too many times, yielding a `too many open files` error that seems irrecoverable.

# Steps to Reproduce

* Create some Idris source file `Source.idr`, possibly valid or invalid it does not matter
* Create an `input` file containing about 50 lines like:
   ```
    :l Source.idr
   ```
* Run `Idris2 < input`

# Observed Behavior

```
Text.Parse> 2/2: Building Text.Parse (Text/Parse.idr)
(implicit):1:1--1:1:Builtin not found
PrimIO> File error in Text/Parse.idr: Too many open files
Main> File error in Text/Parse.idr: Too many open files
Main> File error in Text/Parse.idr: Too many open files
Main> File error in Text/Parse.idr: Too many open files
Main> File error in Text/Parse.idr: Too many open files
Main> File error in Text/Parse.idr: Too many open files
Main> File error in Text/Parse.idr: Too many open files
Main> File error in Text/Parse.idr: Too many open files
```

# Expected Behavior

Files should be closed when reloaded and interpreter should not blow up unless one tries to load 100s or 1000s of files.

**Comment by edwinb** [comment]
Oops! If only we had a type system that could check for this sort of thing :).

Thanks for spotting - I reckon it's worth thinking a bit about how to use QTT to deal with this before we embark too seriously on self hosting, but in the meantime, this is probably a good way in for someone interested in finding their way around the system.

**Comment by clayrat** [comment]
This is weird, because `readFile` used in [`Idris.REPL.loadMainFile`](https://github.com/edwinb/Idris2/blob/master/src/Idris/REPL.idr#L377) already [closes the file it reads from](https://github.com/idris-lang/Idris-dev/blob/master/libs/prelude/Prelude/File.idr#L323).

**Comment by clayrat** [comment]
Also, I get a different error from performing the steps:
```
$ printf ':l Foo.idr\n%.0s' {1..50} > runfoo
$ idris2 < runfoo 
Welcome to Idris 2 version 0.0. Enjoy yourself!
Main> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Parse error: Expected 'case', 'if', 'do', application or operator expression (next 
tokens: [end of input])
Bye for now!
```

**Comment by clayrat** [comment]
Ok, at 204 lines I get a different message:
```
Welcome to Idris 2 version 0.0. Enjoy yourself!
Main> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> Foo> 
:1:1--1:1:Builtin not found
Foo> Parse error: Expected 'case', 'if', 'do', application or operator expression (next 
tokens: [end of input])
```
And then at 205+ lines I start getting the titular message.

**Comment by abailly** [comment]
Yes, the numbers are probably specific to the local environnement

Le mar. 13 août 2019 à 20:24, Alex Gryzlov <notifications@github.com> a
écrit :

**Comment by akuhlens** [comment]
@clayrat, This seems to be failing to reproduce the error. I think the error message that you are getting is due to reaching the end of file input. This can be double checked by just using an empty file as the input stream. Somewhere between 2500 and 2600 loads of the same file causes the original error on my machine.

**Comment by clayrat** [comment]
Yes, the pattern seems to be that first an `:1:1--1:1:Builtin not found` error is produced, and then all subsequent loads generate the `Too many open files` error.

**Comment by clayrat** [comment]
i have found the leak, it's in [`Utils.Binary.readFromFile`](https://github.com/edwinb/Idris2/blob/master/src/Utils/Binary.idr#L77).
