### ISSUE TITLE
can't construct pair using applicative

### ISSUE THREAD

**Issue by shmish111** [edwinb/Idris2-boot#82]
https://gist.github.com/shmish111/0172215916669ae9f5ef822ffcc7c429

# Steps to Reproduce
`idris2 D.idr`

# Expected Behavior
Type checks successfully

# Observed Behavior
```
D.idr:4:39--8:1:While processing right hand side of D.func1 at D.idr:4:1--8:1:
When unifying f d and f d
When unifying f (d -> ?b) and f ((1 y : ?b) -> (c, ?b))
Mismatch between:
	d -> ?b
and
	(1 y : ?b) -> (c, ?b)
```

Note that `func2` in the gist checks just fine so it's something about applying the linear function `Builtin.MkPair : (1 x : a) -> (1 y : b) -> (a, b)`

Also if I use holes
```
func1 f g (a, b) = MkPair <$> ?first <*> ?second
```
I get the type of `?first` as
```
Idris: Type of first
 0 d : Type
 0 b : Type
 0 c : Type
 0 a : Type
 0 f : Type -> Type
   conArg : Applicative f
   b : b
   a : a
   g : b -> f d
   f : a -> f c
-------------------------------------
first : f c
```
No mention of the quantity requirement.

**Comment by edwinb** [comment]
I think this is a limitation in the conversion/unification check, and I'll need to go back to the original rules to be sure of the right way to fix it. We definitely need to do something, but this does have implications for how data types are defined (especially whether it's okay for their arguments to be linear) so I'll take some care over it...

It's unwilling to unify a function which takes a linear argument `(1 x : a) -> b` with a function which takes an unrestricted argument `(x : a) -> b`. e.g. if we're expecting a use-once function with a linear argument, but take a use-once function with an unrestricted argument, we might get more uses than we expect. But they're not use-once functions here, they're unrestricted use, which means it's probably okay. I'm only going to change things when I've convinced myself it's "definitely" rather then "probably" though!

**Comment by shmish111** [comment]
So presumably to fix it that way you would need to say that any function that takes an unrestricted argument can take a linear argument? 

In this case `<$>` expects `(x : a) -> b` but we are giving it `(1 x : a) -> b` but really 'unrestricted' means any number and `1` is a number.

**Comment by edwinb** [comment]
I simplified it a bit more just in case it provided any insight:

    mfunc : (a -> Maybe c) -> (b -> Maybe d) -> (a, b) -> Maybe (c, d)
    mfunc fn g (ma, mb)
       = let pairapp = MkPair <$> fn ma in
             ?whatnext <*> g mb

So we then get:

    D> :t whatnext
     0 d : Type
     0 b : Type
     0 c : Type
     0 a : Type
       mb : b
       ma : a
       g : b -> Maybe d
       fn : a -> Maybe c
       pairapp : Maybe ((1 y : ?b) -> (c, ?b))
    -------------------------------------
    whatnext : Maybe (d -> (c, d))

I think `pairapp` is a perfectly valid solution for `?whatnext` but it seems the typechecker does not agree, so clearly I haven't implemented the rules I thought I had...

I'll get back to this. I'm still supposed to be on holiday and I'm away at ICFP next week! But clearly it needs fixing.
