### ISSUE TITLE
`integerToNat` hangs for negative integers

### ISSUE THREAD

**Issue by shmish111** [edwinb/Idris2-boot#88]
# Steps to Reproduce

`integerToNat (2 - 3)`

# Expected Behavior

Either return `Z` or throw an error

# Observed Behavior

non terminating loop (well it will probably fail eventually when it gets to the last negative integer)

# Extra Info

I came across this because I am working on a project where we want to use natural numbers in both Haskell and Purescript. It turns out that Haskell natural numbers libraries all implement `Num` which in haskell has methods for `negate` and `-`. This means that the library authors chose a certain behaviour (crashing in most cases) in order to get `+` and `*`.

In purescript `+` and `*` are part of the `Semiring` class which is much nicer. There is an integerToNat function defined in `Data.Natural` but it's not part of any standard class because it makes a choice as to what should happen. Similarly there is also a `minus` function that is not part of any class for the same reason.

It seems to me that the way numeric classes work in Purescript is very well thought out and I've now come across a situation where that matters. Could we copy these numeric classes in Idris2 rather than the current classes (`Num`, `Neg` etc), they seem a little more `standard` in terms of it is clear what a `Semiring` is, there are agreed upon rules, the same can't be said for `Num`, for example it is quite different in Haskell and Idris.

So finally there should either be no `integerToNat` defined or it should either crash or return `Z` or possibly have 2 different versions that do different things. `Nat` should not implement a class that has `fromInteger` though.

**Comment by shmish111** [comment]
Or if you _really_ want to implement a class that has `fromInteger` then I think it shouldn't crash and therefore must return `Z`

**Comment by christian-public** [comment]
I also think that `Z` seems like the right choice for negative integers. Created a pull request (#89) to fix this.
