### ISSUE TITLE
fst has the wrong type

### ISSUE THREAD

**Issue by chuckjaz** [edwinb/Idris2-boot#94]
From prelude:

```idr
public export
fst : {0 a, b : Type} -> (a, b) -> a
fst (x, y) = x

public export
snd : {0 a, b : Type} -> (a, b) -> b
snd (x, y) = y
```

should be:

```idr
public export
fst : {a, 0 b : Type} -> (a, b) -> a
fst (x, y) = x

public export
snd : {0 a, b : Type} -> (a, b) -> b
snd (x, y) = y
```

**Comment by clayrat** [comment]
`0` here applies to both `a` and `b`, meaning that these type parameters should be erased at run time. Also your suggested type is not syntactically valid.

**Comment by chuckjaz** [comment]
Free free to close then. 

The precedence of `0` and `1` being lower than `,` is a bit of a surprise.

Also, it seems surprising that both `a` and `b` can be erased when `fst` uses `a` and `snd` uses `b`. As implied by my "fix", only one should be marked as erased.

**Comment by clayrat** [comment]
`fst`/`snd` uses a value of type `a`/`b` at runtime, not the type parameters themselves - these are only needed at compile time.

**Comment by edwinb** [comment]
This is indeed correct. It's an interesting question about the syntax, though. Perhaps {0 a, b : _} should mean that a is erased, but b is not.
